services:
  # MongoDB for task storage
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=swarmonomicon
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
    networks:
      - madness_network

  # Mosquitto MQTT broker for messaging
  mosquitto:
    image: eclipse-mosquitto:2
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    networks:
      - madness_network

  # MCP Todo Server (Omnispindle)
  mcp-todo-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: danedens31/omnispindle:latest
    restart: unless-stopped
    ports:
      - "8000:8000"  # Exposing the Uvicorn port for SSE connections
    environment:
      - MONGODB_URI=mongodb://${AWSIP:-AWS_IP_ADDRESS}:27017
      - MONGODB_DB=swarmonomicon
      - MONGODB_COLLECTION=todos
      - AWSIP=${AWSIP:-AWS_IP_ADDRESS}
      - AWSPORT=${AWSPORT:-1883}
      - MQTT_HOST=${AWSIP:-AWS_IP_ADDRESS}
      - MQTT_PORT=${AWSPORT:-1883}
      - DeNa=omnispindle
      - HOST=0.0.0.0
      - PORT=8000
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    networks:
      - madness_network

  # # Todo Dashboard (optional web UI)
  # todo-dashboard:
  #   build:
  #     context: ./Todomill_projectorium
  #     dockerfile: Dockerfile
  #   image: danedens31/omnispindle-dashboard:latest
  #   restart: unless-stopped
  #   ports:
  #     - "3001:80"
  #   environment:
  #     - API_URL=http://mcp-todo-server:8080
  #   depends_on:
  #     - mcp-todo-server
  #   networks:
  #     - madness_network

networks:
  madness_network:
    driver: bridge
    name: madness_network
    external: true

volumes:
  mongodb_data:
  mosquitto_data:
  mosquitto_log:
